# Data assessing and cleaning

In [11]:
import pandas as pd
import numpy as np
bike_data = pd.read_csv('/Users/gopesh/Documents/Machine Learning/PROJECTS/o5_bikes_data.csv')
bike_data.head(6)

,title,price,kilometer,fuel_type,registration_type,registration_year,owner,color,city,insurance,last_updated,mileage_arai,mileage_owner_reported,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity
0,2011 Hero Honda Splendor Drum,"Rs. 10,000","50,000 km",Not Available,Not Available,Not Available 2011,First,Black,Bhopal,Comprehensive,2 month(s) ago,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,2021 Ducati Monster Standard,Rs. 10.5 Lakh,"2,700 km",Petrol,Not Available,Not Available 2021,Second,Dark Stealth,Mumbai,Not Available,2 month(s) ago,19 kmpl,Not Available,266 km,2,Disc,Disc,Tubeless,14 litres,3.5 litres
2,2022 Bajaj Pulsar Dual Channel ABS [2022],Rs. 1.2 Lakh,"30,009 km",Petrol,Not Available,Not Available 2022,First,Brooklyn Black,Kolkata,Comprehensive,25 day(s) ago,51.6 kmpl,46 kmpl,722 km,1,Disc,Disc,Tubeless,14 litres,2.8 litres
3,2019 Yamaha FZ Single Channel ABS,"Rs. 65,000","50,244 km",Petrol,Not Available,Not Available 2019,First,BLACK,Chennai,Not Available,2 month(s) ago,58 kmpl,46 kmpl,696 km,1,Disc,Drum,Tubeless,12 litres,Not Available
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,"Rs. 80,000","28,000 km",Petrol,Not Available,Nov 2019,First,Black,Bhopal,Not Available,1 month(s) ago,Not Available,38 kmpl,Not Available,1,Disc,Disc,Tubeless,12 litres,2.5 litres
5,2021 TVS Radeon Drum - SBT - BS IV,"Rs. 40,000","46,000 km",Petrol,Not Available,Mar 2021,First,Red,Delhi,Not Available,2 month(s) ago,69.3 kmpl,63 kmpl,690 km,1,Drum,Drum,Tubeless,10 litres,1.5 litres

## Summary of Data

- This data consists of 2777 second hand bikes data which comprises of all the essential things a person looks in a second hand bike before buying it. 

- The data is scraped from an online website Bikewale.com. 

- This dataset covers the data of various tier 1 , tier 2 , tier 3 cities which provides a wide spread of information across the country.

- The main target of this dataset is to predict the price of the second hand bike on the basis of various feature given by the user.

In [12]:
bike_data.columns

Index(['title', 'price', 'kilometer', 'fuel_type', 'registration_type',
       'registration_year', 'owner', 'color', 'city', 'insurance',
       'last_updated', 'mileage_arai', 'mileage_owner_reported',
       'riding_range', 'cylinders', 'front_brake_type', 'rear_brake_type',
       'tyre_type', 'fuel_tank_capacity', 'reserve_fuel_capacity'],
      dtype='object')

## Column Description

- `title` : Name and model of the bike listing, usually including brand and variant

- `price` : Listed selling price of the second-hand bike (typically in INR)

- `kilometer` : Total distance the bike has been ridden, usually in kilometers

- `fuel_type` : Type of fuel the bike uses (e.g., Petrol, Electric)

- `registration_type` : Type of vehicle registration (e.g., Individual, Commercial)

- `registration_year` : Year in which the bike was officially registered

- `owner` : Number/type of previous owners (e.g., First owner, Second owner)

- `color` : Color of the bike as specified in the listing

- `city` : Location (city) where the bike is available for sale

- `insurance` : Insurance status or validity of the bike

- `last_updated` : Timestamp indicating when the listing was last updated

- `mileage_arai` : Official mileage certified under standard testing conditions (ARAI)

- `mileage_owner_reported` : Mileage reported by actual users based on real-world usage

- `riding_range` : Maximum distance the bike can travel on a full tank/charge

- `cylinders` : Number of engine cylinders in the bike

- `front_brake_type` : Type of braking system used in the front wheel (e.g., Disc, Drum)

- `rear_brake_type` : Type of braking system used in the rear wheel

- `tyre_type` : Type of tyres used (e.g., Tubeless, Tube)

- `fuel_tank_capacity` : Total capacity of the fuel tank in liters

- `reserve_fuel_capacity` : Amount of fuel reserved for emergency use after main fuel is low

## Issues with the Dataset :

### 1. Dirty data

- in price column some values contains Lakhs and Rs. so convert it to numeric values. `accuracy` ....
- remove km from kilometers column `accuracy` ....
- registration_type column mostly contains not available column `remove` ....
- extract only year from registration_year from the column `accuracy` ....
- remove last_updated column `remove` ....
- remove kmpl from both mileage columns and replace not available with nan `accuray`....
- remove km from riding range and replace not available with nan`accuracy`
- replace not available with nan values in cylinders `accuracy` ....
- remove liters from both fuel capacity columns and handle not available values `acc` ....
- 986 and 2742 , 539 and 1285 , 1376 and 2352 , 1209 and 2510 , 698 and 1143 , 319 and 2171 , 479 and 1865 , 1957 and 2574 are exact duplicates of each other. `validity` ....
- use describe after converting necessary columns to numeric `describe` ....

### 2. Messy Data

- Extract year , Brand name , model name from title `completeness` ....
- convert these columns to int or float - price , km , reg_year , both mileage , riding_range , cylinders , both tank_capacity `validity` ....

In [13]:
bike_data['reg_year'] = bike_data['title'].str.extract(r'(\d{4})')
bike_data['reg_year'] = bike_data['reg_year'].astype(int)

brands = ["Harley-Davidson","Royal Enfield","Hero Honda","TVS Motor","Moto Guzzi","CFMoto","Husqvarna","Kawasaki","Triumph","Mahindra","Benelli","Keeway","Aprilia","Suzuki",
          "Yamaha","Bajaj","Honda","Hero","TVS","KTM","Jawa","Yezdi","BMW","Ducati","Indian","Ampere Magnus","OLA",
          "Ather","Okinawa","Revolt","Ampere","Ola","Vida","Joy e-bike","PURE EV","Evolet","Bounce","Odysse","Ultraviolette",
          "Vespa","UM","Benling","BSA"]

def extract_brand_name(title) : 
    for brand in brands :
        if brand.lower() in title.lower() :
            return brand 
    return "Unknown"

bike_data['brand_name'] = bike_data['title'].apply(extract_brand_name)  
bike_data1 = bike_data.copy()

bike_data1['temp'] = bike_data1.apply(lambda x: str(x['title']).replace(str(x['reg_year']), '').replace(str(x['brand_name']), ''), axis=1)
bike_data1['model'] = bike_data1['temp'].str.strip().str.replace(r'\s+', ' ', regex=True)
bike_data1.drop(columns=['temp'], inplace=True)

bike_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2777 entries, 0 to 2776
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   2777 non-null   object
 1   price                   2777 non-null   object
 2   kilometer               2777 non-null   object
 3   fuel_type               2777 non-null   object
 4   registration_type       2777 non-null   object
 5   registration_year       2777 non-null   object
 6   owner                   2777 non-null   object
 7   color                   2777 non-null   object
 8   city                    2777 non-null   object
 9   insurance               2777 non-null   object
 10  last_updated            2777 non-null   object
 11  mileage_arai            2777 non-null   object
 12  mileage_owner_reported  2777 non-null   object
 13  riding_range            2777 non-null   object
 14  cylinders               2777 non-null   object
 15  front_brake_type        2777 non-null   object
 16  rear_brake_type         2777 non-null   object
 17  tyre_type               2777 non-null   object
 18  fuel_tank_capacity      2777 non-null   object
 19  reserve_fuel_capacity   2777 non-null   object
 20  reg_year                2777 non-null   int64
 21  brand_name              2777 non-null   object
 22  model                   2777 non-null   object
dtypes: int64(1), object(22)
memory usage: 499.1+ KB

In [14]:
def convert_price(price) : 
    price = str(price)
    price = price.replace('Rs.', '').strip()

    if 'Lakh' in price :
        num = float(price.replace('Lakh', '').strip())
        return num * 100000
    else :
        return float(price.replace(',', '').strip())
    
bike_data1['price'] = bike_data1['price'].astype(str).apply(convert_price)
bike_data1.drop(columns=['registration_year'], inplace=True)
bike_data1.head(5)

,title,price,kilometer,fuel_type,registration_type,owner,color,city,insurance,last_updated,...,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,reg_year,brand_name,model
0,2011 Hero Honda Splendor Drum,10000.0,"50,000 km",Not Available,Not Available,First,Black,Bhopal,Comprehensive,2 month(s) ago,...,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,2011,Hero Honda,Splendor Drum
1,2021 Ducati Monster Standard,1050000.0,"2,700 km",Petrol,Not Available,Second,Dark Stealth,Mumbai,Not Available,2 month(s) ago,...,266 km,2,Disc,Disc,Tubeless,14 litres,3.5 litres,2021,Ducati,Monster Standard
2,2022 Bajaj Pulsar Dual Channel ABS [2022],120000.0,"30,009 km",Petrol,Not Available,First,Brooklyn Black,Kolkata,Comprehensive,25 day(s) ago,...,722 km,1,Disc,Disc,Tubeless,14 litres,2.8 litres,2022,Bajaj,Pulsar Dual Channel ABS []
3,2019 Yamaha FZ Single Channel ABS,65000.0,"50,244 km",Petrol,Not Available,First,BLACK,Chennai,Not Available,2 month(s) ago,...,696 km,1,Disc,Drum,Tubeless,12 litres,Not Available,2019,Yamaha,FZ Single Channel ABS
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,80000.0,"28,000 km",Petrol,Not Available,First,Black,Bhopal,Not Available,1 month(s) ago,...,Not Available,1,Disc,Disc,Tubeless,12 litres,2.5 litres,2019,TVS,Apache Carburetor ABS - Smart Xonnect

In [15]:
import numpy as np
bike_data1['fuel_tank_capacity'] = bike_data1['fuel_tank_capacity'].replace('Not Available' , np.nan)
bike_data1['fuel_tank_capacity'] = bike_data1['fuel_tank_capacity'].str.replace('litres', '').astype(float)

bike_data1['reserve_fuel_capacity'] = bike_data1['reserve_fuel_capacity'].replace('Not Available' , np.nan)
bike_data1['reserve_fuel_capacity'] = bike_data1['reserve_fuel_capacity'].str.replace('litres', '').astype(float)

bike_data1.head(6)

,title,price,kilometer,fuel_type,registration_type,owner,color,city,insurance,last_updated,...,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,reg_year,brand_name,model
0,2011 Hero Honda Splendor Drum,10000.0,"50,000 km",Not Available,Not Available,First,Black,Bhopal,Comprehensive,2 month(s) ago,...,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,2011,Hero Honda,Splendor Drum
1,2021 Ducati Monster Standard,1050000.0,"2,700 km",Petrol,Not Available,Second,Dark Stealth,Mumbai,Not Available,2 month(s) ago,...,266 km,2,Disc,Disc,Tubeless,14.0,3.5,2021,Ducati,Monster Standard
2,2022 Bajaj Pulsar Dual Channel ABS [2022],120000.0,"30,009 km",Petrol,Not Available,First,Brooklyn Black,Kolkata,Comprehensive,25 day(s) ago,...,722 km,1,Disc,Disc,Tubeless,14.0,2.8,2022,Bajaj,Pulsar Dual Channel ABS []
3,2019 Yamaha FZ Single Channel ABS,65000.0,"50,244 km",Petrol,Not Available,First,BLACK,Chennai,Not Available,2 month(s) ago,...,696 km,1,Disc,Drum,Tubeless,12.0,NaN,2019,Yamaha,FZ Single Channel ABS
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,80000.0,"28,000 km",Petrol,Not Available,First,Black,Bhopal,Not Available,1 month(s) ago,...,Not Available,1,Disc,Disc,Tubeless,12.0,2.5,2019,TVS,Apache Carburetor ABS - Smart Xonnect
5,2021 TVS Radeon Drum - SBT - BS IV,40000.0,"46,000 km",Petrol,Not Available,First,Red,Delhi,Not Available,2 month(s) ago,...,690 km,1,Drum,Drum,Tubeless,10.0,1.5,2021,TVS,Radeon Drum - SBT - BS IV

In [16]:
# dropped duplicate rows 
bike_data1.drop([2742 , 1285 , 2352 , 2510 , 1143 , 2171 , 1865 , 2574])

,title,price,kilometer,fuel_type,registration_type,owner,color,city,insurance,last_updated,...,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,reg_year,brand_name,model
0,2011 Hero Honda Splendor Drum,10000.0,"50,000 km",Not Available,Not Available,First,Black,Bhopal,Comprehensive,2 month(s) ago,...,Not Available,Not Available,Not Available,Not Available,Not Available,NaN,NaN,2011,Hero Honda,Splendor Drum
1,2021 Ducati Monster Standard,1050000.0,"2,700 km",Petrol,Not Available,Second,Dark Stealth,Mumbai,Not Available,2 month(s) ago,...,266 km,2,Disc,Disc,Tubeless,14.0,3.5,2021,Ducati,Monster Standard
2,2022 Bajaj Pulsar Dual Channel ABS [2022],120000.0,"30,009 km",Petrol,Not Available,First,Brooklyn Black,Kolkata,Comprehensive,25 day(s) ago,...,722 km,1,Disc,Disc,Tubeless,14.0,2.8,2022,Bajaj,Pulsar Dual Channel ABS []
3,2019 Yamaha FZ Single Channel ABS,65000.0,"50,244 km",Petrol,Not Available,First,BLACK,Chennai,Not Available,2 month(s) ago,...,696 km,1,Disc,Drum,Tubeless,12.0,NaN,2019,Yamaha,FZ Single Channel ABS
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,80000.0,"28,000 km",Petrol,Not Available,First,Black,Bhopal,Not Available,1 month(s) ago,...,Not Available,1,Disc,Disc,Tubeless,12.0,2.5,2019,TVS,Apache Carburetor ABS - Smart Xonnect
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2772,2010 Bajaj Pulsar Standard,30000.0,"4,000 km",Petrol,Not Available,First,Cocktail Wine Red,Surat,Comprehensive,2 month(s) ago,...,510 km,1,Disc,Drum,Tubed,8.0,2.5,2010,Bajaj,Pulsar Standard
2773,2018 Honda Dream Electric Start/Alloy,35000.0,"45,000 km",Petrol,Not Available,First,Black with Heavy Grey Metallic,Surat,Not Available,2 month(s) ago,...,570 km,1,Drum,Drum,Tubeless,8.0,2.3,2018,Honda,Dream Electric Start/Alloy
2774,2020 Suzuki Burgman Standard,85000.0,"17,025 km",Petrol,Not Available,First,Glossy Grey,Bangalore,Not Available,2 month(s) ago,...,322 km,1,Disc,Drum,Tubeless,5.5,1.3,2020,Suzuki,Burgman Standard
2775,2015 Royal Enfield Classic Chrome,100000.0,"95,000 km",Petrol,Not Available,First,Silver,Jaipur,Third Party,2 month(s) ago,...,Not Available,1,Disc,Disc,Tubed,13.0,2.6,2015,Royal Enfield,Classic Chrome
2776,2018 Hero HF Deluxe Drum Brake Self Start,40000.0,"95,125 km",Petrol,Not Available,First,Black Nexus Blue,Nagpur,Third Party,1 day(s) ago,...,Not Available,1,Drum,Drum,Tubeless,9.6,1.0,2018,Hero,HF Deluxe Drum Brake Self Start

In [17]:
bike_data1['cylinders'] = bike_data1['cylinders'].replace('Not Available' , np.nan)
bike_data1['cylinders'] = bike_data1['cylinders'].astype(float)
bike_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2777 entries, 0 to 2776
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   2777 non-null   object
 1   price                   2777 non-null   float64
 2   kilometer               2777 non-null   object
 3   fuel_type               2777 non-null   object
 4   registration_type       2777 non-null   object
 5   owner                   2777 non-null   object
 6   color                   2777 non-null   object
 7   city                    2777 non-null   object
 8   insurance               2777 non-null   object
 9   last_updated            2777 non-null   object
 10  mileage_arai            2777 non-null   object
 11  mileage_owner_reported  2777 non-null   object
 12  riding_range            2777 non-null   object
 13  cylinders               2549 non-null   float64
 14  front_brake_type        2777 non-null   object
 15  rear_brake_type         2777 non-null   object
 16  tyre_type               2777 non-null   object
 17  fuel_tank_capacity      2541 non-null   float64
 18  reserve_fuel_capacity   2190 non-null   float64
 19  reg_year                2777 non-null   int64
 20  brand_name              2777 non-null   object
 21  model                   2777 non-null   object
dtypes: float64(4), int64(1), object(17)
memory usage: 477.4+ KB

In [18]:
bike_data1.describe()

,price,cylinders,fuel_tank_capacity,reserve_fuel_capacity,reg_year
count,2.777000e+03,2549.000000,2541.000000,2190.000000,2777.000000
mean,1.047950e+05,1.036877,11.341834,2.072740,2019.360101
std,1.157322e+05,0.213858,3.208497,0.752726,4.635640
min,2.032000e+03,1.000000,2.000000,0.000000,1980.000000
25%,4.500000e+04,1.000000,10.000000,1.400000,2017.000000
50%,7.500000e+04,1.000000,12.000000,2.000000,2020.000000
75%,1.350000e+05,1.000000,13.000000,2.600000,2023.000000
max,1.900000e+06,4.000000,21.000000,5.200000,2026.000000

In [20]:
bike_data1 = bike_data1[~((bike_data1['kilometer'] > 250000) & (bike_data1['reg_year'] > 2012))]
bike_data1 = bike_data1[~((bike_data1['mileage_arai'] > 70) & (bike_data1['mileage_owner_reported'] > 70))]
bike_data1.describe()

ValueError: invalid literal for int() with base 10: '50,000'

In [ ]:
bike_data1[bike_data1['mileage_owner_reported'] > 70]
bike_data1.drop([368 , 544 , 794 , 1608] , inplace=True)

In [21]:
bike_data1.loc[2294 , 'price'] = 180000 
bike_data1.describe()

,price,cylinders,fuel_tank_capacity,reserve_fuel_capacity,reg_year
count,2.777000e+03,2549.000000,2541.000000,2190.000000,2777.000000
mean,1.041756e+05,1.036877,11.341834,2.072740,2019.360101
std,1.106104e+05,0.213858,3.208497,0.752726,4.635640
min,2.032000e+03,1.000000,2.000000,0.000000,1980.000000
25%,4.500000e+04,1.000000,10.000000,1.400000,2017.000000
50%,7.500000e+04,1.000000,12.000000,2.000000,2020.000000
75%,1.350000e+05,1.000000,13.000000,2.600000,2023.000000
max,1.700000e+06,4.000000,21.000000,5.200000,2026.000000

In [ ]:
bike_data1.loc[2067 , 'fuel_tank_capacity'] = 10.0
bike_data1.loc[2067 , 'riding_range'] = 700
bike_data1.describe()

,price,kilometer,mileage_arai,mileage_owner_reported,riding_range,cylinders,fuel_tank_capacity,reserve_fuel_capacity,reg_year,"(2294, price)"
count,2.720000e+03,2720.000000,1253.000000,2500.000000,1288.000000,2496.000000,2489.000000,2149.000000,2720.000000,2720.0
mean,1.047063e+05,31039.702574,51.548444,44.012200,517.280280,1.037660,11.354399,2.075682,2019.411029,180000.0
std,1.106738e+05,27290.882504,15.898753,10.503899,194.924124,0.216049,3.201996,0.748484,4.560108,0.0
min,2.032000e+03,1.000000,13.000000,13.000000,65.000000,1.000000,3.000000,0.500000,1983.000000,180000.0
25%,4.500000e+04,12000.000000,40.000000,35.000000,330.000000,1.000000,10.000000,1.400000,2017.000000,180000.0
50%,7.500000e+04,25000.000000,50.000000,45.000000,554.000000,1.000000,12.000000,2.000000,2020.000000,180000.0
75%,1.400000e+05,43092.500000,61.000000,50.000000,663.750000,1.000000,13.000000,2.600000,2023.000000,180000.0
max,1.700000e+06,351282.000000,95.000000,75.000000,970.000000,4.000000,21.000000,4.500000,2026.000000,180000.0

In [ ]:
# bike_data1 = bike_data1.iloc[:, :20]
bike_data1[bike_data1['riding_range'] == 970]
bike_data1.loc[382 , 'riding_range'] = 600

In [ ]:
bike_data1.describe()

,price,kilometer,mileage_arai,mileage_owner_reported,riding_range,cylinders,fuel_tank_capacity,reserve_fuel_capacity,reg_year
count,2.720000e+03,2720.000000,1253.000000,2500.000000,1288.000000,2496.000000,2489.000000,2149.000000,2720.000000
mean,1.047063e+05,31039.702574,51.548444,44.012200,516.993012,1.037660,11.354399,2.075682,2019.411029
std,1.106738e+05,27290.882504,15.898753,10.503899,194.528655,0.216049,3.201996,0.748484,4.560108
min,2.032000e+03,1.000000,13.000000,13.000000,65.000000,1.000000,3.000000,0.500000,1983.000000
25%,4.500000e+04,12000.000000,40.000000,35.000000,330.000000,1.000000,10.000000,1.400000,2017.000000
50%,7.500000e+04,25000.000000,50.000000,45.000000,554.000000,1.000000,12.000000,2.000000,2020.000000
75%,1.400000e+05,43092.500000,61.000000,50.000000,660.000000,1.000000,13.000000,2.600000,2023.000000
max,1.700000e+06,351282.000000,95.000000,75.000000,950.000000,4.000000,21.000000,4.500000,2026.000000

In [22]:
bike_data1.drop([314] , inplace=True)
bike_data1[bike_data1['kilometer'] < 20]

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
bike_data1.describe()

,price,kilometer,mileage_arai,mileage_owner_reported,riding_range,cylinders,fuel_tank_capacity,reserve_fuel_capacity,reg_year
count,2.716000e+03,2716.000000,1252.000000,2496.000000,1287.000000,2492.000000,2485.000000,2145.000000,2716.000000
mean,1.045771e+05,31085.407953,51.549681,44.019832,516.773116,1.037319,11.352837,2.075077,2019.412739
std,1.104809e+05,27284.950739,15.905046,10.504923,194.444065,0.215357,3.199906,0.748459,4.553521
min,2.032000e+03,10.000000,13.000000,13.000000,65.000000,1.000000,3.000000,0.500000,1983.000000
25%,4.500000e+04,12000.000000,40.000000,35.000000,330.000000,1.000000,10.000000,1.400000,2017.000000
50%,7.500000e+04,25000.000000,50.000000,45.000000,550.000000,1.000000,12.000000,2.000000,2020.000000
75%,1.362500e+05,43125.000000,61.000000,50.000000,660.000000,1.000000,13.000000,2.600000,2023.000000
max,1.700000e+06,351282.000000,95.000000,75.000000,950.000000,4.000000,21.000000,4.500000,2026.000000

In [ ]:
cols = ['title', 'reg_year', 'brand_name', 'model', 'kilometer', 
        'fuel_type', 'owner', 'city', 'color', 'insurance',
        'mileage_arai', 'mileage_owner_reported', 'riding_range', 
        'cylinders', 'front_brake_type', 'rear_brake_type', 
        'tyre_type', 'fuel_tank_capacity', 'reserve_fuel_capacity' , 'price']

bike_data1 = bike_data1[cols]
bike_data1.head()

,title,reg_year,brand_name,model,kilometer,fuel_type,owner,city,color,insurance,mileage_arai,mileage_owner_reported,riding_range,cylinders,front_brake_type,rear_brake_type,tyre_type,fuel_tank_capacity,reserve_fuel_capacity,price
0,2011 Hero Honda Splendor Drum,2011,Hero Honda,Splendor Drum,50000,Not Available,First,Bhopal,Black,Comprehensive,NaN,NaN,NaN,NaN,Not Available,Not Available,Not Available,NaN,NaN,10000.0
1,2021 Ducati Monster Standard,2021,Ducati,Monster Standard,2700,Petrol,Second,Mumbai,Dark Stealth,Not Available,19.0,NaN,266.0,2.0,Disc,Disc,Tubeless,14.0,3.5,1050000.0
2,2022 Bajaj Pulsar Dual Channel ABS [2022],2022,Bajaj,Pulsar Dual Channel ABS [],30009,Petrol,First,Kolkata,Brooklyn Black,Comprehensive,51.6,46.0,722.0,1.0,Disc,Disc,Tubeless,14.0,2.8,120000.0
3,2019 Yamaha FZ Single Channel ABS,2019,Yamaha,FZ Single Channel ABS,50244,Petrol,First,Chennai,BLACK,Not Available,58.0,46.0,696.0,1.0,Disc,Drum,Tubeless,12.0,NaN,65000.0
4,2019 TVS Apache Carburetor ABS - Smart Xonnect,2019,TVS,Apache Carburetor ABS - Smart Xonnect,28000,Petrol,First,Bhopal,Black,Not Available,NaN,38.0,NaN,1.0,Disc,Disc,Tubeless,12.0,2.5,80000.0

In [23]:
bike_data1.to_csv('bikes_data_cleaned.csv' , index=False)

In [25]:
bike_data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2776 entries, 0 to 2776
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   title                   2776 non-null   object
 1   price                   2776 non-null   float64
 2   kilometer               2776 non-null   object
 3   fuel_type               2776 non-null   object
 4   registration_type       2776 non-null   object
 5   owner                   2776 non-null   object
 6   color                   2776 non-null   object
 7   city                    2776 non-null   object
 8   insurance               2776 non-null   object
 9   last_updated            2776 non-null   object
 10  mileage_arai            2776 non-null   object
 11  mileage_owner_reported  2776 non-null   object
 12  riding_range            2776 non-null   object
 13  cylinders               2548 non-null   float64
 14  front_brake_type        2776 non-null   object
 15  rear_brake_type         2776 non-null   object
 16  tyre_type               2776 non-null   object
 17  fuel_tank_capacity      2540 non-null   float64
 18  reserve_fuel_capacity   2189 non-null   float64
 19  reg_year                2776 non-null   int64
 20  brand_name              2776 non-null   object
 21  model                   2776 non-null   object
dtypes: float64(4), int64(1), object(17)
memory usage: 498.8+ KB